name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.1.0
      - run: uv lock --check
      - run: uv sync --extra dev
      - run: uv run wing-demo-run --duration 2
      # pytest not available for now
