[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

board_build.filesystem = littlefs

upload_speed = 115200
monitor_speed = 115200

# Set these to your machine's serial port
# upload_port = COM7
# monitor_port = COM7

lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    waspinator/AccelStepper

build_flags =
    -DMQTT_MAX_PACKET_SIZE=512

build_src_filter =
    +<main.cpp>
    +<hardware/*.cpp>
    +<comms/*.cpp>
    +<utils/*.cpp>
    -<*_test.cpp>
